import type {Metadata} from "next";
import {Open_Sans} from "next/font/google";
import {PropsWithChildren} from "react";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: PropsWithChildren) {
  return (
    <html lang="en">
    <body className={`${openSans.className}`}>
    {children}
    </body>
    </html>
  );
}
