import type {Metadata} from "next";
import {Open_Sans} from "next/font/google";
import {PropsWithChildren} from "react";
import "./globals.css";
import AuthProvider from "@/app/(auth)/Provider";
import SessionGuard from "@/app/(auth)/SessionGuard";
import {ToastContainer} from "react-toastify";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "TaskBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({children}: PropsWithChildren) {
  return (
    <html lang="en">
    <body className={`${openSans.className}`}>
    <AuthProvider>
      <SessionGuard>
        <main>{children}</main>
      </SessionGuard>
      <ToastContainer
        position="top-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="light"
      />
    </AuthProvider>
    </body>
    </html>
  );
}
