CREATE TABLE users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT users_pkey PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    email VARCHAR(255) NOT NULL,
    fullname VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    is_verified BOOLEAN DEFAULT FALSE
);

CREATE TABLE signup_verification_records
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT signup_verification_records_pkey PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6),
    token VARCHAR(255) NOT NULL,
    user_email VARCHAR(255) NOT NULL
);

CREATE TABLE tasks
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT tasks_pkey PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    description VARCHAR(512) NOT NULL,
    priority VARCHAR(50) NOT NULL CONSTRAINT tasks_priority_check CHECK ((priority)::TEXT = ANY ((ARRAY ['LOW'::VARCHAR, 'MEDIUM'::VARCHAR, 'HIGH'::VARCHAR])::TEXT[])),
    status VARCHAR(50) NOT NULL CONSTRAINT tasks_status_check CHECK ((status)::TEXT = ANY ((ARRAY ['TODO'::VARCHAR, 'IN_PROGRESS'::VARCHAR, 'COMPLETED'::VARCHAR])::TEXT[])),
    title VARCHAR(255) NOT NULL,
    user_id BIGINT CONSTRAINT fk6s1ob9k4ihi75xbxe2w0ylsdh REFERENCES users
);

CREATE TABLE reset_password_records
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT reset_password_records_pkey PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6),
    token VARCHAR(255) NOT NULL,
    user_email VARCHAR(255) NOT NULL
);